version = "2026.05.06.01"
release_date = "2026-05-06T17:00:00Z"
description = "Official rule set for Griffon Scanner"

[[rules]]
name = "ransomware"
filename = "rules/yara/ransomware.yar"

[[rules]]
name = "apt"
filename = "rules/yara/apt.yar"

[[rules]]
name = "known-backdoor"
filename = "rules/yara/backdoors.yar"

[[rules]]
name = "known-cryptominer"
filename = "rules/yara/cryptominers.yar"

[[rules]]
name = "known-spyware"
filename = "rules/yara/spyware.yar"

[[rules]]
name = "trojans"
filename = "rules/yara/trojans.yar"

[[rules]]
name = "webshells"
filename = "rules/yara/webshells.yar"

[[rules]]
name = "other"
filename = "rules/yara/other.yar"
